name: Cypress Testing Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'  # Run daily at 4 AM

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
        browser: [chrome, firefox, edge]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Cypress tests
      run: npm run cypress:run -- --browser ${{ matrix.browser }}
      
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        gh_pages: gh-pages
        allure_report: allure-report
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-results-${{ matrix.browser }}-${{ matrix.node-version }}
        path: |
          cypress/screenshots/
          cypress/videos/
          allure-results/
          
    - name: Comment PR with test results
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          const comment = `## 🧪 Cypress Test Results
          
          **Browser:** ${{ matrix.browser }}
          **Node Version:** ${{ matrix.node-version }}
          **Status:** ${{ job.status }}
          
          ### Test Summary
          - ✅ All Cypress tests executed successfully
          - 📊 Test reports generated
          - 📸 Screenshots and videos captured
          - 🔍 Cross-browser compatibility verified
          
          **View detailed reports:** [Allure Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report/)
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
